name: Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  linter:
    # Name the Job
    name: Detekt
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Detekt
        run: ./gradlew detekt
        env:
          BATHYSPHERE_GOOGLE_SIGN_IN_CLIENT_ID: ${{ secrets.BATHYSPHERE_GOOGLE_SIGN_IN_CLIENT_ID }}
          BATHYSPHERE_GOOGLE_SIGN_IN_CLIENT_SECRET: ${{ secrets.BATHYSPHERE_GOOGLE_SIGN_IN_CLIENT_SECRET }}
          BATHYSPHERE_KEYSTORE_PASSWORD: ${{ secrets.BATHYSPHERE_KEYSTORE_PASSWORD }}
